Parenting
========================================================


```{r packages}
library (ggplot2) ; library ('lme4');library ("mediation"); library ("foreign") ; library ('lmerTest');  library ('plyr');library(dplyr); library (tidyr); library ('car'); library ('Rmisc')
```


**read the file **
```{r readfile}


d = read.csv("AGEC1_study3_data.csv")




d$condition = factor(d$condition, label = c("low anger", "high anger", "control"))

d$important = factor(d$important , label =c ("low importance", "high importance"))
d$unit = factor (d$unit , label =c ("low unity", "high unity"))


d1 = subset (d, condition == "low anger" | condition == "high anger")

d1$condition = as.numeric (d1$condition)
d1$unit = as.numeric (d1$unit)

```


#important

```{r important}

r = lm (agree_important ~ important, d) ; summary (r)

r = lm (important1 ~ important, d) ; summary (r)
r = lm (important2 ~ important, d) ; summary (r)
 # working in the other direction here for some reason, 


```


#unity

```{r unity}

r = lm (agree_unit ~ unit, d) ; summary (r)

r = lm (unit1 ~ unit, d) ; summary (r)
r = lm (unit2 ~ unit, d) ; summary (r)
r = lm (unit3 ~ unit, d) ; summary (r)

#all is working 

detach("package:dplyr", unload=TRUE)

library (car)
d$runit2 = recode(d$unit2,"7=1;6=2;5=3;4=4;3=5;2=6;1=7")   


alpha (d[,c('unit1', 'runit2', 'unit3')], delete = TRUE)


head(reliability (d[,c('unit1', 'runit2', 'unit3')], itema = TRUE, NA.Delete = TRUE))

d$unitscale = (rowMeans(d[,c( 'runit2', 'unit3')], na.rm=T))

r = lm (unitscale ~ unit, d) ; summary (r)
confint (r,  level = 0.95)

d %>%
  group_by(unit) %>%
  summarise(sd(unitscale, na.rm = T))

```


```{r perliminary analysis}

r= lm (express~ Age , d) ; summary (r)
confint (r,  level = 0.95)

r= lm (express~ sex , d) ; summary (r)
confint (r,  level = 0.95)

a= length (d$white)

ethnic =c(black = sum(d$black)/a, latino = sum(d$latino)/a,white= sum(d$white)/a,asian = sum(d$asian)/a, other= sum(d$other_ethnic)/a)

ethnic= round(ethnic,3)

ethnic
```


```{r main effect}

r = lm(express ~ condition , d) ; summary (r)
confint (r, level =.95)

d %>%
  group_by(condition) %>%
  summarise(sd(express, na.rm = T))

table (d$condition)


```




**interaction 
```{r interaction }
d$unit1 = as.integer(d$unit1)
d1$condition = as.integer(d1$condition)

summary (d1$condition)


r = lm(express ~ scale(unit1)* scale(condition), d) ; summary (r)
confint (r, levle = .95)



d1 = subset (d, condition == "low anger" | condition == "high anger")

levels(d1$unit)
r = lm(express ~ unit* condition, d1) ; summary (r)
confint (r, levle = .95)

d1$runit <- relevel(d1$unit, "high unity")
levels(d1$rcondition)

r = lm(express ~ runit* condition, d1) ; summary (r)
confint (r, levle = .95)



d1 %>%
  group_by( unit) %>% 
  do(r = print(summary(lm(express ~ condition, data = .))))


# look at the simple effects in a way that looks at condicdence intervals. 


d1$condition = factor (d1$condition , label = c("Low Anger", "High Anger"))

d1$unit = factor (d1$unit , label =c ("low unity", "high unity"))



#### graph the results ### 

dc <- summarySE(d1, measurevar="express", groupvars=c("condition","unit"))

pd <- position_dodge(.1)

g = (ggplot(dc,aes(x=unit, y=express ,fill = condition, ymax =max(express)))
  + geom_errorbar(aes(ymin=express-ci, ymax=express+ci), width=.1) 
  + geom_line( aes(linetype= condition, group=condition),size = 1.2) 
  +geom_point() 
  +scale_y_continuous(limits = c(3, 5))
   +scale_colour_manual(values = c("#000000", "#000000")) 

   +scale_linetype_manual(values=c("solid", "dotted")) 
  +theme_bw()
  +theme(legend.title=element_blank(),axis.title.y = element_text(  size=14),axis.text.x  = element_text( vjust=0.5, size=14),axis.text.y  = element_text( vjust=0.5, size=12),axis.title.x = element_text(vjust=0.5, size=14)) 
  
  +labs(title = "Anger Responses", x = "Support in Parental Unity", y = ""))

g;



#### bar graph of the results
dc <- summarySE(d, measurevar="express", groupvars=c("condition","unit"))

dc$cont_condition <- ordered(dc$condition, levels = c("high anger", "control", "low anger"))

dc$cont_condition = factor(dc$cont_condition, label = c("High anger", "Control", "Low anger"))
dc

dc$unit = factor (dc$unit, label = c("Low unity", "High unity"))

pd <- position_dodge(.1)

cbPalette <- c("#CCCCCC", "#666666", "#333333")


ggplot(dc, aes(x=unit, y=express, fill=cont_condition)) + 
    geom_bar(position=position_dodge(), stat="identity", colour="black" ) +
    labs(title = "Anger responses", x = "Support in parental unity", y = "")+
    theme_bw()+
  guides(fill = guide_legend(override.aes = list(colour = NULL)))+
    #facet_wrap( ~ par, ncol=2)+
      theme(axis.title.y = element_text(size=14),axis.text.x  = element_text( vjust=0.5, size=14),axis.text.y=element_text( vjust=0.5, size=14),axis.title.x = element_blank(), legend.title = element_blank()) + 
  coord_cartesian(ylim=c(1, 7)) +
    ylab("Anger responses")+
    scale_fill_manual(values=cbPalette)+
  geom_errorbar(aes(ymin=express-ci, ymax=express+ci),
                  width=.1,position=position_dodge(.9))




```
